#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers.sh

log_info "Symlinking git configs"

TARGET="${HOME}"

configs=(
  ".gitconfig"
  ".gitignore_global"
)
for config in "${configs[@]}"; do
  config_source="$(dirname "$0")/${config}"
  log_debug "Symlinking ${config_source} to ${TARGET}/${config}"
  ln -sfnw "${config_source}" "${TARGET}/${config}"
done
