#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking zsh configs"

TARGET="${HOME}"

configs=(
  ".zshrc"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done

log_info "Symlinking OMZ configs"
ZSH="${ZSH:-${HOME}/.oh-my-zsh}"
ZSH_CUSTOM="${ZSH_CUSTOM:-${ZSH}/custom}"
TARGET="${ZSH_CUSTOM}"
mkdir -p "${TARGET}"

configs=(
  "agnoster.zsh-theme"
  "aliases.zsh"
  "path.zsh"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
