#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking AWS configs"

TARGET="${HOME}/.aws"
mkdir -p "${TARGET}"
clean_broken_symlinks "${TARGET}"

configs=(
  "config"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
