#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking bash configs, scripts, and utilities"

TARGET="${HOME}"

configs=(
  ".bashrc"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
