#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking bash configs, scripts, and utilities"

TARGET="${HOME}"

# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html
#
# /etc/profile: This is a system-wide initialization file that is executed during login. This file provides initial environment variables and initial "PATH" locations.
# /etc/bashrc: This again is a system-wide initialization file. This file is executed each time a Bash shell is opened by a user. Here you can define your default prompt and add alias information. Values in this file can be overridden by their local ~/.bashrc entry.
# ~/.bash_profile: If this file exists, it is executed automatically after /etc/profile during the login process. This file can be used by each user to add individual entries. The file however is only executed once at login and normally then runs the users .bashrc file.
# ~/.bash_login: If the .bash_profile does not exist, then this file will be executed automatically at login.
# ~/.profile: If the .bash_profile or .bash_login do not exist, then this file is executed automatically at login.
# ~/.bashrc: This file contains individual specific configurations. This file is read at login and also each time a new Bash shell is started. Ideally, this is where you should place any aliases.
# ~/.bash_logout: This file is executed automatically during logout.
# ~/.inputrc: This file is used to customize key bindings/key strokes.
# ~/.bash_aliases: Keeps your alias collection neat and tidy. Source it in .bashrc with a line like `if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi`.
configs=(
  ".bash_profile"
  ".bash_login"
  ".profile"
  ".bashrc"
  ".bash_logout"
  ".inputrc"
  ".bash_aliases"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
