#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_attention "FYI: Docker cannot write to symlinked config files; Copying from templates instead"
log_info "Copying docker config templates"

TARGET="${HOME}/.docker"
mkdir -p "${TARGET}"

json_configs=(
  "config"
  "daemon"
)
for config in "${json_configs[@]}"; do

  if [[ -L "${TARGET}/${config}.json" ]]; then
    unlink "${TARGET}/${config}.json"
  elif [[ -e "${TARGET}/${config}.json" ]]; then
    log_attention "${TARGET}/${config}.json already exists; skipping"
    exit 0
  elif [[ ! -e "${config}.template.json" ]]; then
    log_attention "Could not find ${config}.template.json; skipping"
    exit 0
  fi

  cp "${config}.template.json" "${TARGET}/${config}.json"
done
