#!/bin/sh

set -e

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi

git config --global --unset url."git@github.com:".insteadOf

apt-get install -y \
  zsh-autosuggestions \
  zsh-syntax-highlighting

if [ -d "$HOME/zsh-git-prompt" ]
then
  echo "Updating zsh-git-prompt..."
  (cd "$HOME/zsh-git-prompt" && git pull)
else
  echo "Cloning zsh-git-prompt..."
  git clone https://github.com/olivierverdier/zsh-git-prompt.git "$HOME/zsh-git-prompt"
fi
