#!/usr/bin/env sh
set -eu

# You can add a script file to your dotfiles repo that will be executed when the
# dotfiles are loaded into your Codespaces. You do have to give it the proper
# name, but GitHub gives you several to choose from. When Codespaces detects a
# script file in your dotfiles repo, it clones the dotfiles repo to
# "/workspaces/.codespaces/.persistedshare/dotfiles" and then executes your
# script file if it exists. If it does not find an applicable script file then
# it will copy and files starting with "." from the dotfiles directory to the
# $HOME folder in the codespace. If it does find a script, then it expects the
# script to copy over the dotfiles to the correct place.
#
# https://docs.github.com/en/codespaces/setting-your-user-preferences/personalizing-github-codespaces-for-your-account#dotfiles

[ -z "${CODESPACES:-}" ] && exit 0

# ENV variables we could evaluate in a Codespace:
# CLOUDENV_ENVIRONMENT_ID=very-long-guid-hash
# CODESPACES=true # Always true if set
# CODESPACES_RECOVERY_CONTAINER=true|false
# CODESPACE_NAME=name-plus-guid
# CODESPACE_VSCODE_FOLDER=/workspaces/mycoolapp
# CONTAINER_BUILDER_TOKEN=github-token
# GITHUB_API_URL=https://api.github.com
# GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=app.github.dev
# GITHUB_CODESPACE_TOKEN=LONG_TOKEN
# GIT_COMMITTER_EMAIL=noreply@github.com
# GITHUB_GRAPHQL_URL=https://api.github.com/graphql
# GITHUB_REPOSITORY=me/mycoolapp
# GITHUB_SERVER_URL=https://github.com
# GITHUB_TOKEN=another-github-token
# GITHUB_USER=me
# HOST=codespaces-${short-token}
# HOSTNAME=codespaces-${short-token}
# RepositoryName=mycoolapp
# TERM_PROGRAM=vscode # Could also be "codespaces"

echo "Starting codespace specific bootstrap..."

echo "Unsetting git url config for github.com..."
git config --global --unset url."git@github.com:".insteadOf

echo "Checking if linuxbrew is installed..."
if [ -d "/home/linuxbrew/.linuxbrew" ]; then
  echo "Initializing linuxbrew into zprofile..."
  echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "${HOME}/.zprofile"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

echo "Done codespace specific bootstrapping!"
