#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."

# Check for Homebrew and install if we don't have it
/usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/chrisbloom7/dotfiles/HEAD/script/install-homebrew)"
eval "$($(command -v brew) shellenv)"

brew tap homebrew/bundle
brew tap homebrew/services

# Install prerequisite Homebrew formulae
brew install --require-sha --no-quarantine --force --verbose \
  coreutils \
  git \
  gpg-suite \
  mas \
  zsh \
2>&1 | tee /tmp/brew-prerequisites.log

# Install Xcode via mas
# https://github.com/mas-cli/mas
mas install 497799835 2>&1 | tee /tmp/installl-xcode.log

# Install Xcode Command Line Tools
xcode-select --install 2>&1 | tee /tmp/xcode-command-line-tools.log
