#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."

# Check for Homebrew and install if we don't have it
if [ -z $(command -v brew 2>/dev/null) ]; then
  /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 2>&1 | tee /tmp/brew-install.log
fi

echo "Homebrew installed at $(command -v brew 2>/dev/null)"
