#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."

# Mackup currently has a bug that makes it dangerous to use with Sonoma. The
# workaround is to run `mackup backup -f` or `mackup restore -f` and then
# immediately run `mackup uninstall -f`. This tricks mackup into creating or
# restoring the backup files, during which it's usual symlinking process will
# fail. Then, when it tries to uninstall, it will copy the files back to their
# original locations. This script will then symlink files that were linked in
# the fresh script in case mackup trampled on them.

# Symlink the Mackup config files to the home directory.
# Make sure Mackup is excluded from backing itself up
[ -s "$HOME/.mackup.cfg" ] && rm -rf "$HOME/.mackup.cfg"
ln -s "$HOME/.dotfiles/.mackup.cfg" "$HOME/.mackup.cfg"

# Symlink the Mackup custom app config files to the home directory.
[ -s "$HOME/.mackup" ] && rm -rf "$HOME/.mackup"
ln -s "$HOME/.dotfiles/.mackup" "$HOME/.mackup"

export RBENV_ROOT="$(rbenv root)"
[ -s "$RBENV_ROOT/default-gems" ] && rm -rf "$RBENV_ROOT/default-gems"
ln -s "$HOME/.dotfiles/default-gems" "$RBENV_ROOT/default-gems"
