#!/usr/bin/env bash

SCRIPT_NAME=${1:-"script/setup"}

# Send all our -x output to this file for later debugging
LOG_DIR="$HOME/setup.logs"
mkdir -p "${LOG_DIR}"
exec 1>"${LOG_DIR}/stdout"
exec 2>"${LOG_DIR}/stderr"
exec 19>"${LOG_DIR}/trace"
BASH_XTRACEFD=19

set -x

echo "${SCRIPT_NAME} start: $(date)"

# DOTFILES_ROOT=$(pwd -P)

set -e

echo ""

if [ -z "$ZSH" ]
then
  echo "Setting ZSH..."
  ZSH="$HOME/.oh-my-zsh"
fi

if [ -z "$ZSH_CUSTOM" ]
then
  echo "Setting ZSH_CUSTOM..."
  ZSH_CUSTOM="$ZSH/custom"
fi

# Check for Oh My Zsh and install if we don't have it
if [ -d "$ZSH" ]
then
  if [ -d "$ZSH_CUSTOM" ]
  then
    echo "Oh My Zsh custom folder already exists, deleting and recreating it"
    rm -rf  "$ZSH_CUSTOM"
    mkdir -p "$ZSH_CUSTOM"
  fi
else
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)" "" --unattended
fi

# (ssh-keygen -F github.com || ssh-keyscan github.com) >> ~/.ssh/known_hosts

if [ -d "/workspaces/.codespaces/.persistedshare/dotfiles" ]
then
  echo "Copying git config files..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.gitignore_global" "$HOME/.gitignore_global"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.gitconfig" "$HOME/.gitconfig"
  git config --global --unset url."git@github.com:".insteadOf

  echo "Copying omz scripts..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/aliases.zsh" "$ZSH_CUSTOM/aliases.zsh"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/agnoster.zsh-theme" "$ZSH_CUSTOM/agnoster.zsh-theme"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/path.zsh" "$ZSH_CUSTOM/path.zsh"

  if [ -f "$HOME/.zshrc" ]
  then
    echo "Removing default .zshrc..."
    rm -rf "$HOME/.zshrc"
  fi
  echo "Copying custom .zshrc..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.zshrc" "$HOME/.zshrc"
else
  echo "MISSING /workspaces/.codespaces/.persistedshare/dotfiles"
fi

echo ""
echo "🏁 All installed! 🏁"
