#!/bin/sh

if [ -z "$ZSH" ]
then
  echo "Setting ZSH..."
  ZSH="$HOME/.oh-my-zsh"
fi

if [ -z "$ZSH_CUSTOM" ]
then
  echo "Setting ZSH_CUSTOM..."
  ZSH_CUSTOM="$ZSH/custom"
fi

# Check for Oh My Zsh and install if we don't have it
if [ -d "$ZSH" ]
then
  echo "Oh My Zsh already installed..."
  mkdir -p "$ZSH_CUSTOM"
else
  echo "Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)" "" --unattended
fi

if [ -d "/workspaces/.codespaces/.persistedshare/dotfiles" ]
then
  echo "Copying git config files..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.gitignore_global" "$HOME/.gitignore_global"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.gitconfig" "$HOME/.gitconfig"
  git config --global --unset url."git@github.com:".insteadOf

  echo "Copying omz scripts..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/aliases.zsh" "$ZSH_CUSTOM/aliases.zsh"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/agnoster.zsh-theme" "$ZSH_CUSTOM/agnoster.zsh-theme"
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/path.zsh" "$ZSH_CUSTOM/path.zsh"

  if [ -f "$HOME/.zshrc" ]
  then
    echo "Removing default .zshrc..."
    rm -rf "$HOME/.zshrc"
  fi

  echo "Copying custom .zshrc..."
  cp "/workspaces/.codespaces/.persistedshare/dotfiles/.zshrc" "$HOME/.zshrc"
else
  echo "MISSING /workspaces/.codespaces/.persistedshare/dotfiles"
fi

echo "Cloning omz plugins..."
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-autosuggestions.git "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
git clone https://github.com/zsh-users/zsh-completions.git "$ZSH_CUSTOM/plugins/zsh-completions"

echo "Cloning zsh-git-prompt..."
git clone https://github.com/olivierverdier/zsh-git-prompt.git "$HOME/zsh-git-prompt"
