#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."

DOTFILES="${DOTFILES:-$(pwd)}"

if [ -n $(command -v rbenv) ]; then 
  export RBENV_ROOT="$(rbenv root)"

  echo "Symlinking default gems for rbenv from '${DOTFILES}' to '${RBENV_ROOT}'..."
  [ -s "$RBENV_ROOT/default-gems" ] && rm -rf "$RBENV_ROOT/default-gems"
  ln -sfn "$DOTFILES/default-gems" "$RBENV_ROOT/default-gems"
fi
