#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."

DOTFILES="${DOTFILES:-$(pwd)}"

echo "Symlinking mise global config from '${DOTFILES}' to '${HOME}'..."
mkdir -p "${HOME}/.config/mise"
[ -s "${HOME}/.config/mise/config.toml" ] && rm -rf "${HOME}/.config/mise/config.toml"
ln -sfn "${DOTFILES}/mise-config-global.toml" "${HOME}/.config/mise/config.toml"

echo "Symlinking default gems for mise from '${DOTFILES}' to '${HOME}'..."
[ -s "${HOME}/.default-gems" ] && rm -rf "${HOME}/.default-gems"
ln -sfn "${DOTFILES}/default-gems" "${HOME}/.default-gems"
