#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking Mackup configs"

TARGET="${HOME}"

# NOTE: Be sure Mackup is excluded from backing itself up!
configs=(
  ".mackup.cfg"
  ".mackup"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
