#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking ruby configs"

TARGET="${HOME}"

configs=(
  ".autotest"
  ".devpack"
  ".gemrc"
  ".irbrc"
  ".pryrc"
  ".rspec"
  ".rvmrc"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done

log_debug "Symlinking default-gems to ~/ as .default-gems"
symlink_config "${PWD}/default-gems" "${TARGET}/.default-gems"

log_debug "Symlinking .bundle-config to ~/ as .bundle/config"
mkdir -p "${TARGET}/.bundle"
clean_broken_symlinks "${TARGET}/.bundle"
symlink_config "${PWD}/.bundle-config" "${TARGET}/.bundle/config"

if [[ -n $(command -v rbenv 2>/dev/null) ]]; then
  TARGET="${RBENV_ROOT:-$(rbenv root)}"
  log_debug "Symlinking default-gems for rbenv"
  symlink_config "${PWD}/default-gems" "${TARGET}/default-gems"
fi
