#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking ruby configs"

TARGET="${HOME}"

configs=(
  ".irbrc"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done

log_debug "Symlinking default-gems to ~/ as .default-gems"
symlink_config "${PWD}/default-gems" "${TARGET}/.default-gems"

log_debug "Symlinking .bundle-config to ~/ as .bundle/config"
symlink_config "${PWD}/.bundle-config" "${TARGET}/.bundle/config"

if [[ -n $(command -v rbenv 2>/dev/null) ]]; then
  # Symlink default-gems to second custom target
  TARGET="${RBENV_ROOT:-$(rbenv root)}"
  log_debug "Symlinking default-gems to rbenv"
  symlink_config "${PWD}/default-gems" "${TARGET}/default-gems"
fi
