[settings]
experimental = false
legacy_version_file = true
lockfile = false
trusted_config_paths = ["~/.mise.local.toml"]
idiomatic_version_file_enable_tools = ["node", "ruby", "ruby"]

[tools]
aws-vault = "latest"
