#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers.sh

log_info "Symlinking mise configs"

if [[ -n $(command -v mise 2>/dev/null) ]]; then
  TARGET="${HOME}/.config/mise"
  mkdir -p "${TARGET}"

  log_debug "Symlinking mise global config to ${TARGET}/config.toml"
  ln -sfnw config.toml "${TARGET}/config.toml"
fi
