#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./helpers.sh

# Uncomment this next line and commit the change to make dotfile installs into
# any new codespaces a no-op. Useful for debugging devcontainer builds without
# worrying about whether your dotfiles are causing issues.
# [[ -n "${CODESPACES:-}" ]] && exit 0

log_info "Bootstrapping"

ZSH="${ZSH:-${HOME}/.oh-my-zsh}"
ZSH_CUSTOM="${ZSH_CUSTOM:-${ZSH}/custom}"
ZSH_PATH="${ZSH_PATH:-$(command -v zsh 2>/dev/null)}"

log_info "checking for zsh and OMZ"
if [[ -n "${ZSH_PATH}" ]]; then
  # Check for Oh My Zsh and install if we don't have it
  if [[ ! -d "${ZSH}" ]]; then
    log_info "Installing Oh My Zsh"
    /usr/bin/env bash -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  fi

  mkdir -p "${ZSH_CUSTOM}"

  # Set zsh as the default
  log_info "Setting ZSH as the default shell"
  sudo chsh -s "$(command -v zsh 2>/dev/null)"
fi

if [[ -n "${CODESPACES:-}" ]]; then
  log_debug "Using codepsaces dotfiles"
  DOTFILES="/workspaces/.codespaces/.persistedshare/dotfiles"
else
  log_debug "Using local dotfiles"
  DOTFILES="${DOTFILES:-$(pwd)}"
fi

# Symlink config files applicable to local and remote development
log_debug "calling config symlink script"
./symlink-config-files

if [[ -n "${CODESPACES:-}" ]]; then
  log_debug "calling codespaces bootstrap script"
  ./codespaces-bootstrap
fi

if [[ -n "${ZSH_PATH}" ]] && [[ -d "${ZSH_CUSTOM}" ]]; then
  log_debug "Installing OMZ plugins"
  mkdir -p "${ZSH_CUSTOM}/plugins"
  plugins=(
    "zsh-syntax-highlighting"
    "zsh-autosuggestions"
    "zsh-completions"
    "zsh-history-substring-search"
  )
  for plugin in "${plugins[@]}"; do
    if [[ ! -d "${ZSH_CUSTOM}/plugins/${plugin}" ]]; then
      log_debug "Installing ${plugin} to ${ZSH_CUSTOM}/plugins"
      git clone https://github.com/zsh-users/${plugin}.git "${ZSH_CUSTOM}/plugins/${plugin}"
    fi
  done
fi

log_success "Done bootstrapping!"
