#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./helpers/runtime.sh
source ../bin/helpers/trap_and_trace.sh

# Local macOS setup, not in a devcontainer
log_info "Bootstrapping macOS"

if [[ "$(is_macos)" != "true" && "$(is_linux)" != "true" ]]; then
  log_attention "Not a macOS or Linux workstation; skipping $0"
  exit 0
fi

# Run setup steps that apply both locally and in devcontainers
log_debug "Running setup steps that apply both locally and in devcontainers"
./bootstrap-common

log_debug "Sourcing homebrew script"
source ./helpers/source_homebrew.sh

log_info "Adding Homebrew evals to shell profiles"
add_eval_to_dotfile "[[ -f \"$(brew --prefix)/bin/brew\" ]]" "\"$(brew --prefix)/bin/brew\" shellenv" "${HOME}/.bash_profile" "${HOME}/.zprofile"

# log_info "Adding HOMEBREW_CASK_OPTS to shell profiles"
# if [[ "$(is_macos)" == "true" ]]; then
#   add_eval_to_dotfile "" "export HOMEBREW_CASK_OPTS=\"--appdir=\\\"${HOME}/Applications\\\" --fontdir=\\\"${HOME}/Library/Fonts\\\"\"" "${HOME}/.bash_profile" "${HOME}/.zprofile"
# # else
# #   add_eval_to_dotfile "" "export HOMEBREW_CASK_OPTS=\"--require-sha\"" "${HOME}/.bash_profile" "${HOME}/.zprofile"
# fi

log_debug "Updating Homebrew"
if is_verbose_mode; then
  brew_args="--verbose"
elif is_quiet_mode; then
  brew_args="--quiet"
else
  brew_args=""
fi
brew update $brew_args

log_info "Installing Homebrew support for upgrading casks"
brew tap buo/cask-upgrade

if is_force_mode; then
  brew_args="${brew_args} --force"
fi

# TODO: --display-times is not supported on brew bundle
# if ! is_quiet_mode; then
#   brew_args="${brew_args} --display-times"
# fi

log_debug "Disabling Exit on error for Homebrew bundle/upgrade"
if [[  $- =~ e ]]; then
  set +e
  RESTORE_EXIT_ON_ERROR=true
fi
if is_update_mode; then
  log_info "Upgrading existing Homebrew packages"
  log_debug "Running brew upgrade with args: ${brew_args}"
  brew upgrade $brew_args
else
  # To restrict app installations to current user, add args:
  #   --appdir "${HOME}/Applications" --fontdir "${HOME}/Library/Fonts"
  log_info "Installing minimal Homebrew packages from Brewfile"
  bundle_args="${brew_args} --no-upgrade"
  log_debug "Running brew bundle with args: ${bundle_args}"
  brew bundle --file ../Brewfile.minimal $bundle_args
fi
log_debug "Re-enabling Exit on error"
if [[ ${RESTORE_EXIT_ON_ERROR:-} == true ]]; then
  set -e
  unset RESTORE_EXIT_ON_ERROR
fi

if ! is_minimal_mode && ! is_update_mode; then
  # To restrict app installations to current user, add args:
  #   --appdir "${HOME}/Applications" --fontdir "${HOME}/Library/Fonts"
  deserialize_array ADDITIONAL_DEPENDENCIES_SERIALIZED ADDITIONAL_DEPENDENCIES '|'
  for dependency_suffix in "${ADDITIONAL_DEPENDENCIES[@]}"; do
    log_info "Installing additional Homebrew packages from Brewfile.${dependency_suffix}"
    log_debug "Disabling Exit on error for Brewfile.${dependency_suffix}"
    if [[  $- =~ e ]]; then
      set +e
      RESTORE_EXIT_ON_ERROR=true
    fi
    log_debug "Running brew bundle with args: ${bundle_args}"
    brew bundle --file ../Brewfile.${dependency_suffix} $bundle_args
    log_debug "Re-enabling Exit on error"
    if [[ ${RESTORE_EXIT_ON_ERROR:-} == true ]]; then
      set -e
      unset RESTORE_EXIT_ON_ERROR
    fi
  done

  if ! is_skip_local_mode; then
    log_info "Looking for local Brewfiles in $(cd ../ && pwd)"

    oldIFS=$IFS && IFS=$'\n'
    local_brewfiles=($(find ../ \( -type f -or -type l \) -maxdepth 1 -name "Brewfile*.local" -print))
    IFS=$oldIFS

    for brewfile in "${local_brewfiles[@]}"; do
      log_info "Installing additional Homebrew packages from ${brewfile}"
      log_debug "Disabling Exit on error for ${brewfile}"
      if [[  $- =~ e ]]; then
        set +e
        RESTORE_EXIT_ON_ERROR=true
      fi
      log_debug "Running brew bundle with args: ${bundle_args}"
      brew bundle --file "${brewfile}" $bundle_args
      log_debug "Re-enabling Exit on error"
      if [[ ${RESTORE_EXIT_ON_ERROR:-} == true ]]; then
        set -e
        unset RESTORE_EXIT_ON_ERROR
      fi
    done
  else
    log_debug "SKIP_LOCAL_MODE is enabled; skipping search for Brewfile*.local files"
  fi
fi

log_info "Cleaning up Homebrew services"
brew services cleanup ${brew_args}

log_info "Cleaning up stale lock files and outdated downloads for Homebrew"
brew_cleanup_args="${brew_args} --prune=all"
if ! is_verbose_mode; then
  # This command is particularly noisy; only show output in verbose mode
  brew_cleanup_args="${brew_cleanup_args} --quiet"
fi
brew cleanup ${brew_cleanup_args}

if ! is_minimal_mode && ! is_update_mode; then
  # Uninstall default Mac apps
  log_debug "Checking for mas CLI"
  if [[ -n "$(command -v mas 2>/dev/null)" ]]; then
    log_info "Uninstalling default Mac apps"
    mas uninstall 408981434 || true # iMovie
    mas uninstall 409183694 || true # Keynote
    # mas uninstall 409201541 || true # Pages
    # mas uninstall 409203825 || true # Numbers
  fi

  # Set default MySQL root password and auth type
  log_debug "Checking for MySQL"
  if [[ -n "$(command -v mysql 2>/dev/null)" ]]; then
    log_info Setting a blank root password for MySQL...
    brew services start mysql
    mysql -u root -e "ALTER USER root@localhost IDENTIFIED BY ''; FLUSH PRIVILEGES;"
    brew services stop mysql
  fi
fi

if [[ -n "$(command -v mise 2>/dev/null)" ]]; then
  if ! is_update_mode; then
    log_info "Activating Mise"
    add_eval_to_dotfile '[[ -n "$(command -v mise 2>/dev/null)" ]]' "mise activate bash"   "${HOME}/.bash_profile"
    add_eval_to_dotfile '[[ -n "$(command -v mise 2>/dev/null)" ]]' "mise completion bash" "${HOME}/.bash_completion"
    add_eval_to_dotfile '[[ -n "$(command -v mise 2>/dev/null)" ]]' "mise activate zsh"    "${HOME}/.zprofile"
    # add_eval_to_dotfile '[[ -f "~/.local/bin/mise" ]]' "~/.local/bin/mise completion zsh"  "/usr/local/share/zsh/site-functions/_mise"
    eval "$(~/.local/bin/mise activate bash)"
  fi

  mise_args="--cd $HOME --env local --yes"
  if is_verbose_mode; then
    mise_args="${mise_args} --verbose"
  elif is_quiet_mode; then
    mise_args="${mise_args} --quiet"
  fi
  if is_update_mode; then
    log_info "Updating installed Mise plugins"
    log_debug "Running mise upgrade with args: ${mise_args}"
    mise upgrade $mise_args
  else
    mise_plugins="python node@lts"
    if ! is_minimal_mode; then
      mise_plugins="${mise_plugins} go java@lts ruby rust"
    fi
    log_info "Installing Mise plugins"
    log_debug "Running mise use with args: ${mise_args} ${mise_plugins}"
    mise use $mise_args $mise_plugins
  fi

  log_info "Reshimming Mise plugins"
  mise_reshim_args="--cd $HOME --yes"
  if is_force_mode; then
    mise_reshim_args="${mise_reshim_args} --force"
  fi
  log_debug "Running mise reshim with args: ${mise_reshim_args}"
  mise reshim $mise_reshim_args
else
  log_attention "Mise not found; skipping Mise setup"
fi

# Clone project repositories
if ! is_minimal_mode && ! is_update_mode; then
  log_debug "calling clone-projects script"
  ./clone-projects
fi

# Install iTerm2 shell integration for Zsh
log_info "Installing iTerm2 shell integration for Zsh"
curl -L https://iterm2.com/misc/install_shell_integration.sh | zsh

# Install Rosetta 2 on M1+ Macs to bridge the gap between Intel and Apple processors
if [[ "$(uname -m)" =~ "arm" ]] && [[ -n $(command -v softwareupdate 2>/dev/null) ]]; then
  log_info "Installing Rosetta 2"
  softwareupdate --install-rosetta --agree-to-license || true
fi

# Set macOS preferences - we run this last because this will reload the shell
if ! is_minimal_mode && ! is_update_mode; then
  log_debug "calling configure-macos script"
  ./configure-macos
fi

# Re-symlink Mackup config files to the home directory after setup
log_debug "calling config symlink script"
./symlink-config-files

log_attention "Some changes may require a logout/restart to take effect"
log_attention "You may need to manually set fonts in your terminal profiles"

log_success "Done codespace specific bootstrapping!"
