#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./helpers/runtime.sh
source ../bin/helpers/trap_and_trace.sh

if [[ "$(is_macos)" != "true" && "$(is_linux)" != "true" ]]; then
  log_error "This script only supports macOS and Linux"
  exit 1
fi

log_info "Installing prerequisites"

# Check for Homebrew and install if we don't have it
log_info "Checking for Homebrew"
SOURCE_HOMEBREW_SILENT=true source ./helpers/source_homebrew.sh
if [[ -z $(command -v brew 2>/dev/null) ]]; then
  log_info "Installing Homebrew"
  /usr/bin/env bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

log_info "Initializing Homebrew"
source ./helpers/source_homebrew.sh

# Install prerequisite Homebrew formulae
log_info "Installing prerequisite Homebrew formulae"
brew_args=(--require-sha --no-quarantine --overwrite)
if is_force_mode; then
  brew_args+=(--force)
fi
if is_verbose_mode; then
  brew_args+=(--verbose)
elif is_quiet_mode; then
  brew_args+=(--quiet)
fi
if ! is_quiet_mode; then
  brew_args+=(--display-times)
fi

if [ -z "$(brew ls coreutils 2>/dev/null)" ]; then
  log_info "Installing coreutils formulae"
  brew install "${brew_args[@]}" coreutils
fi

if [ -z "$(brew ls git 2>/dev/null)" ]; then
  log_info "Installing git formulae"
  brew install "${brew_args[@]}" git
fi

if [ -z "$(brew ls gpg-suite 2>/dev/null)" ]; then
  log_info "Installing gpg-suite formulae"
  brew install "${brew_args[@]}" gpg-suite
fi

if [ -z "$(brew ls zsh 2>/dev/null)" ]; then
  log_info "Installing zsh formulae"
  brew install "${brew_args[@]}" zsh
fi

if [ -z "$(brew ls bats-core 2>/dev/null)" ]; then
  log_info "Installing bats-core formulae"
  brew install "${brew_args[@]}" bats-core
fi

if [[ "$(is_macos)" == "true" ]]; then
  if [ -z "$(brew ls mas 2>/dev/null)" ]; then
    log_info "Installing mas formulae"
    brew install "${brew_args[@]}" mas
  fi

  if [[ -z $(command -v xcode-select 2>/dev/null) ]]; then
    # Install Xcode via mas
    # https://github.com/mas-cli/mas
    log_info "Installing Xcode via Mac App Store"
    mas install 497799835
  fi

  # Install Xcode Command Line Tools
  if [[ -z "$(xcode-select --print-path 2>/dev/null)" ]]; then
    log_info "Installing Xcode Command Line Tools"
    xcode-select --install
  fi
fi

log_success "Prerequisites installed!"
