#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./helpers/runtime.sh
source ../bin/helpers/trap_and_trace.sh

if [[ "$(is_macos)" != "true" && "$(is_linux)" != "true" ]]; then
  log_error "This script only supports macOS and Linux"
  exit 1
fi

log_info "Installing prerequisites"

# Check for Homebrew and install if we don't have it
log_info "Checking for Homebrew"
SOURCE_HOMEBREW_SILENT=true source ./helpers/source_homebrew.sh
if [[ -z $(command -v brew 2>/dev/null) ]]; then
  log_info "Installing Homebrew"
  /usr/bin/env bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

log_info "Initializing Homebrew"
source ./helpers/source_homebrew.sh

# Install prerequisite Homebrew formulae
log_info "Installing prerequisite Homebrew formulae"
brew_args="--require-sha --no-quarantine --overwrite"
if is_force_mode; then
  brew_args="$brew_args --force"
fi
if is_verbose_mode; then
  brew_args="$brew_args --verbose"
elif is_quiet_mode; then
  brew_args="$brew_args --quiet"
fi
if ! is_quiet_mode; then
  brew_args="$brew_args --display-times"
fi

log_debug "Checking for coreutils formulae"
if [ -z "$(brew ls coreutils 2>/dev/null)" ]; then
  log_info "Installing coreutils formulae"
  brew install $brew_args coreutils
fi

log_debug "Checking for git formulae"
if [ -z "$(brew ls git 2>/dev/null)" ]; then
  log_info "Installing git formulae"
  brew install $brew_args git
fi

log_debug "Checking for gpg-suite formulae"
if [ -z "$(brew ls gpg-suite 2>/dev/null)" ]; then
  log_info "Installing gpg-suite formulae"
  brew install $brew_args gpg-suite
fi

log_debug "Checking for zsh formulae"
if [ -z "$(brew ls zsh 2>/dev/null)" ]; then
  log_info "Installing zsh formulae"
  brew install $brew_args zsh
fi

# Check for bats-core
log_debug "Checking for bats-core formulae"
if [ -z "$(brew ls bats-core 2>/dev/null)" ]; then
  log_info "Installing bats-core formulae"
  brew install $brew_args bats-core
fi

if [[ "$(is_macos)" == "true" ]]; then
  log_debug "Checking for mas formulae"
  if [ -z "$(brew ls mas 2>/dev/null)" ]; then
    log_info "Installing mas formulae"
    brew install $brew_args mas
  fi

  log_debug "Checking for xcode-select"
  if [[ -z $(command -v xcode-select 2>/dev/null) ]]; then
    # Install Xcode via mas
    # https://github.com/mas-cli/mas
    log_info "Installing Xcode via Mac App Store"
    mas install 497799835
  fi

  # Install Xcode Command Line Tools
  log_debug "Checking for Xcode Command Line Tools"
  if [[ -z "$(xcode-select --print-path 2>/dev/null)" ]]; then
    log_info "Installing Xcode Command Line Tools"
    xcode-select --install
  fi
fi

log_success "Prerequisites installed!"


# install_code_dependencies() {
#     print_progress "Setting up mise package manager & installing dependencies..."
#     cd $PORTAL_DIR
#     errors=0

#     # install everything in .tool-versions
#     if check_err "mise install"; then errors=1; fi
#     mise use --global aws-vault@latest
#     mise settings add idiomatic_version_file_enable_tools ruby

#     source "${SHELL_STARTUP_FILE}"

#     mise_gem=$(mise which gem)
#     mise_bundle=$(mise which bundle)
#     mise_yarn=$(mise which yarn)

#     print_progress "Installing gems & node packages..."
#     if check_err "${mise_gem} install foreman"; then errors=1; fi
#     # overmind is installed via brew on macOS
#     if [[ $PLATFORM != "Darwin" ]]; then
#         if check_err "${mise_gem} install overmind"; then errors=1; fi
#     fi
#     pg_config="pg_config"
#     if [[ $PLATFORM = "Darwin" ]]; then
#         pg_config="$(brew --prefix libpq)/bin/pg_config"
#     fi
#     if check_err "${mise_bundle} config build.pg --with-pg-config=$pg_config &> /dev/null"; then errors=1; fi
#     if check_err "${mise_bundle} install"; then errors=1; fi
#     if check_err "${mise_yarn} install"; then errors=1; fi

#     if [[ errors -eq 0 ]]; then
#         print_success "mise set up & dependencies installed."
#     else
#         print_failure "There were errors installing dependencies, some dependencies may not have been installed."
#     fi
# }

# install_homebrew() {
#     print_progress "Checking for Homebrew install..."
#     not_used=$(brew help)
#     if [[ $? -ne 0 ]]; then
#         print_warning "Homebrew not found."
#         print_progress "Installing Homebrew..."
#         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#         print_success "Homebrew installed."
#     else
#         print_success "Homebrew already installed."
#     fi
# }

# install_xcode_command_tools() {
#     print_progress "Installing Xcode command line tools..."
#     not_used=$(git --version)
#     if [[ $? -ne 0 ]]; then
#         if check_err "xcode-select --install"; then
#             print_failure "Failed to install Xcode command line tools."
#             return
#         else
#             print_warning 'Requested installation of Xcode command line tools.
# You may need to download them from System Settings > General > Software Update.
# Once you have done so and verified commands like "make" and "git" work, press ENTER to continue...'
# read _
#         fi
#         print_success "Xcode command line tools installed."
#     else
#         print_success "Xcode command line tools already installed."
#     fi
# }

# update_shell_startup_file() {
#     print_progress "Modifying ${SHELL_STARTUP_FILE}..."
#     add_to_file_once "$SHELL_STARTUP_FILE" "eval \$(/opt/homebrew/bin/brew shellenv)"
#     add_to_file_once "$SHELL_STARTUP_FILE" "eval \"\$(mise activate $(basename $SHELL))\""
#     source "$SHELL_STARTUP_FILE"
#     print_success "${SHELL_STARTUP_FILE} updated."
# }

# setup_brew_environment() {
#     print_progress "Checking on Brew environment..."
#     if [[ -z "${HOMEBREW_PREFIX}" ]]; then
#         print_warning "Brew environment not set up."
#         print_progress "Setting up Brew environment..."
#         source "${SHELL_STARTUP_FILE}"
#     fi
#     print_success "Brew environment set up."
# }

# install_brew_dependencies() {
#     print_progress "Installing Brew dependencies..."
#     cd $PORTAL_DIR
#     eval "$(brew --prefix)/bin/brew update"
#     eval "$(brew --prefix)/bin/brew bundle install"
#     eval "$(brew --prefix)/bin/brew install --cask docker"
#     eval "$(brew --prefix)/bin/brew install jq"
#     eval "$(brew --prefix)/bin/brew upgrade"
#     source "$SHELL_STARTUP_FILE"
#     print_success "Brew dependencies installed."
#     print_warning "Please open the Docker application (Finder > Applications > Docker), then come back and press ENTER..."
#     read _
# }

# set_no_mac_keychain_timeout() {
#     print_progress "Setting aws-vault keychain to have no timeout..."
#     if check_err "security set-keychain-settings aws-vault.keychain-db"; then
#         print_failure "Failed to unset aws-vault keychain timeout"
#         return
#     fi
#     print_success "aws-vault keychain timeout unset"
# }
