#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./helpers/runtime.sh
source ../bin/helpers/trap_and_trace.sh

if [[ "$(is_macos)" != "true" && "$(is_linux)" != "true" ]]; then
  log_error "This script only supports macOS and Linux"
  exit 1
fi

log_info "Installing prerequisites"

# Check for Homebrew and install if we don't have it
log_info "Checking for Homebrew"
if [[ -z $(command -v brew 2>/dev/null) ]]; then
  log_info "Installing Homebrew"
  /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ -d ~/.linuxbrew ]]; then
  log_debug "Homebrew installed at ~/.linuxbrew"
  eval "$(~/.linuxbrew/bin/brew shellenv)"
elif [[ -d /home/linuxbrew/.linuxbrew ]]; then
  log_debug "Homebrew installed at /home/linuxbrew/.linuxbrew"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ -d /opt/homebrew ]]; then
  log_debug "Homebrew installed at opt/homebrew"
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -n "$(command -v brew 2>/dev/null)" ]]; then
  brew_command="$(command -v brew 2>/dev/null)"
  log_debug "Homebrew installed at $(dirname "${brew_command}")"
  eval "$(${brew_command} shellenv)"
else
  log_error "Could not locate Homebrew installation location
  exit 1
fi

log_info "Setting up Homebrew taps"
[[ -n "$(brew tap | grep homebrew/bundle)" ]] || brew tap --quiet homebrew/bundle
[[ -n "$(brew tap | grep homebrew/services)" ]] || brew tap --quiet homebrew/services

# Install prerequisite Homebrew formulae
log_info "Installing prerequisite Homebrew formulae"
brew_args="--require-sha --no-quarantine --force --overwrite"
if is_verbose_mode; then
  brew_args="$brew_args --verbose"
else
  brew_args="$brew_args --quiet"
fi

log_debug "Checking for coreutils formulae"
if [ -z "$(brew ls coreutils)" ]; then
  log_info "Installing coreutils formulae"
  brew install $brew_args coreutils
fi

log_debug "Checking for git formulae"
if [ -z "$(brew ls git)" ]; then
  log_info "Installing git formulae"
  brew install $brew_args git
fi

log_debug "Checking for gpg-suite formulae"
if [ -z "$(brew ls gpg-suite)" ]; then
  log_info "Installing gpg-suite formulae"
  brew install $brew_args gpg-suite
fi

log_debug "Checking for zsh formulae"
if [ -z "$(brew ls zsh)" ]; then
  log_info "Installing zsh formulae"
  brew install $brew_args zsh
fi

# Check for bats-core
log_debug "Checking for bats-core formulae"
if [ -z "$(brew ls bats-core)" ]; then
  log_info "Installing bats-core formulae"
  brew install $brew_args bats-core
fi

if [[ "$(is_macos)" == "true" ]]; then
  log_debug "Checking for mas formulae"
  if [ -z "$(brew ls mas)" ]; then
    log_info "Installing mas formulae"
    brew install $brew_args mas
  fi

  # Install Xcode via mas
  # https://github.com/mas-cli/mas
  log_info "Installing Xcode via Mac App Store"
  mas install 497799835

  # Install Xcode Command Line Tools
  log_info "Installing Xcode Command Line Tools"
  if [[ -z "$(xcode-select --print-path 2>/dev/null)" ]]; then
    xcode-select --install
  fi
fi

log_success "Prerequisites installed!"
